name: Swift

on:
  push:
    branches: [ main ]
    paths: "swift-dione-crypto"
  pull_request:
    branches: [ main ]
    paths: "swift-dione-crypto"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
      working-directory: swift-dione-crypto
    - name: Run tests
      run: swift test -v
      working-directory: swift-dione-crypto
